import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./items/component/navbar";
import Footer from "./items/component/footer";
import { Suspense } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Suspense fallback={<div>Loading...</div>}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen bg-[#ffe5d4] text-[#440806]`}
        >
          <div className="p-8">
            {" "}
            <Navbar />{" "}
          </div>
          {children}

          <Footer />
        </body>{" "}
      </Suspense>
    </html>
  );
}
